nopSolutions/nopCommerce

src/Presentation/Nop.Web/Controllers/TopicController.cs, src/Presentation/Nop.Web/Views/Topic/TopicBlock.cshtml, src/Presentation/Nop.Web/Views/Topic/TopicDetails.cshtml
Html.AntiForgeryToken added to the following views:
- TopicBlock.cshtml
- TopicDetails.cshtml
=> XSRF validation for authenticating password protected topics

src/Presentation/Nop.Web.Framework/Mvc/NopModelBinder.cs, src/Presentation/Nop.Web/Models/Customer/ChangePasswordModel.cs, src/Presentation/Nop.Web/Models/Customer/LoginModel.cs, src/Presentation/Nop.Web/Models/Customer/PasswordRecoveryConfirmModel.cs, src/Presentation/Nop.Web/Models/Customer/RegisterModel.cs, src/Presentation/Nop.Web/Models/Install/InstallModel.cs
Dear @andreymaz;
I enjoyed your way to make the solution general. I made a little changes, I think after adding **NoTrim** attribute it's better to remove hard coded **DataType.Password**.
=> #194 Little more changes on trimming to make it more general.

src/Presentation/Nop.Web/Administration/Controllers/CustomerController.cs
Ensured for valid email address if registered role is checked to avoid customers registered with empty email address
=> #1143 Ensured for valid email address if registered role is checked

src/Libraries/Nop.Services/Messages/MessageTokenProvider.cs
Four new tokens for Facebook, Twitter, YouTube and Google Plus are added in message templates.
=> #1119 Message Tokens for social network pages are added.

src/Libraries/Nop.Services/Catalog/CategoryService.cs, src/Libraries/Nop.Services/Catalog/IManufacturerService.cs, src/Libraries/Nop.Services/Catalog/ManufacturerService.cs, src/Libraries/Nop.Services/ExportImport/ImportManager.cs
Optimization search of non-existent categories
Implemented global validation of the existence of the manufacturers
=>  #186 Further changes to import products refactoring.

src/Libraries/Nop.Core/IWebHelper.cs, src/Libraries/Nop.Core/WebHelper.cs, src/Libraries/Nop.Services/Common/PdfService.cs, src/Libraries/Nop.Services/Directory/GeoLookupService.cs, src/Libraries/Nop.Services/Helpers/UserAgentHelper.cs, src/Libraries/Nop.Services/Installation/CodeFirstInstallationService.cs, src/Libraries/Nop.Services/Installation/SqlFileInstallationService.cs, src/Libraries/Nop.Services/Media/PictureService.cs, src/Plugins/Nop.Plugin.Widgets.NivoSlider/NivoSliderPlugin.cs, src/Presentation/Nop.Web.Framework/Menu/XmlSiteMap.cs, src/Presentation/Nop.Web.Framework/Security/FilePermissionHelper.cs, src/Presentation/Nop.Web.Framework/Themes/ThemeProvider.cs, src/Presentation/Nop.Web/Administration/Controllers/CommonController.cs, src/Presentation/Nop.Web/Administration/Controllers/JbimagesController.cs, src/Presentation/Nop.Web/Administration/Controllers/LanguageController.cs, src/Presentation/Nop.Web/Controllers/CommonController.cs, src/Presentation/Nop.Web/Controllers/InstallController.cs, src/Presentation/Nop.Web/Infrastructure/Installation/InstallationLocalizationService.cs
All calls changed to static CommonHelper.MapPath
=> MapPath from IWebHelper/WebHelper removed #1234

src/Presentation/Nop.Web/Administration/Views/Language/List.cshtml, src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml
=> Add flag image in Language List

src/Presentation/Nop.Web/Controllers/BlogController.cs, src/Presentation/Nop.Web/Controllers/BoardsController.cs, src/Presentation/Nop.Web/Controllers/NewsController.cs, src/Presentation/Nop.Web/Controllers/ProductController.cs
=> Add check for secure Connection #988

src/Libraries/Nop.Services/Catalog/ProductService.cs, src/Presentation/Nop.Web.Framework/Kendoui/Dynamic.cs, src/Presentation/Nop.Web.Framework/Kendoui/Filter.cs, src/Presentation/Nop.Web.Framework/Themes/ThemeConfiguration.cs, src/Presentation/Nop.Web/Infrastructure/Installation/InstallationLocalizationService.cs
Simplify Expressions second try
#1276
=> Simplify Expressions

src/Libraries/Nop.Core/CommonHelper.cs, src/Libraries/Nop.Services/Customers/CustomerService.cs, src/Libraries/Nop.Services/Customers/ICustomerService.cs, src/Presentation/Nop.Web/Administration/Controllers/CustomerController.cs, src/Presentation/Nop.Web/Administration/Models/Customers/CustomerListModel.cs, src/Presentation/Nop.Web/Administration/Views/Customer/List.cshtml, src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml, src/Tests/Nop.Core.Tests/CommonHelperIpAddressValidatorTests.cs, src/Tests/Nop.Core.Tests/Nop.Core.Tests.csproj, upgradescripts/3.70-the next version/upgrade.sql
=> Filter Customer by IP

src/Libraries/Nop.Core/Domain/Common/CommonSettings.cs, src/Libraries/Nop.Services/Customers/DeleteGuestsTask.cs, src/Libraries/Nop.Services/Installation/CodeFirstInstallationService.cs, src/Presentation/Nop.Web/App_Data/Install/create_required_data.sql, upgradescripts/3.70-the next version/upgrade.sql
Interval was hard coded to 1440.  Move to
Tasks.DeleteGuestTask.OlderThanMinutes setting.
=> Add adjustable configuration for DeleteGuestTask

src/Tests/Nop.Web.MVC.Tests/Nop.Web.MVC.Tests.csproj
Fixed some references that prevented the solution from building properly.
=> Fixed messed up project reference

src/Libraries/Nop.Services/Localization/LocalizationService.cs, src/Libraries/Nop.Services/Orders/OrderReportService.cs, src/Plugins/Nop.Plugin.Shipping.USPS/USPSComputationMethod.cs, src/Presentation/Nop.Web/Administration/Controllers/RoxyFilemanController.cs
Remove duplicate assign variables and fix comparison variable
=> fix bugs and micro refactoring

src/Libraries/Nop.Core/Html/CodeFormatter/SourceFormat.cs, src/Libraries/Nop.Core/Plugins/OfficialFeedManager.cs, src/Libraries/Nop.Services/Helpers/BrowscapXmlParser.cs, src/Libraries/Nop.Services/Messages/EmailSender.cs, src/Libraries/Nop.Services/Security/EncryptionService.cs, src/Libraries/Nop.Services/Seo/SitemapGenerator.cs, src/Plugins/Nop.Plugin.ExternalAuth.Facebook/Core/FacebookProviderAuthorizer.cs, src/Plugins/Nop.Plugin.Shipping.UPS/UPSComputationMethod.cs, src/Plugins/Nop.Plugin.Shipping.USPS/USPSComputationMethod.cs, src/Presentation/Nop.Web/Administration/Controllers/RoxyFilemanController.cs
small refactoring to make use of "using" for correct disposing
=> encapsulate Streams with using

src/Libraries/Nop.Services/Messages/INewsLetterSubscriptionService.cs, src/Libraries/Nop.Services/Messages/NewsLetterSubscriptionService.cs, src/Presentation/Nop.Web/Administration/Controllers/NewsLetterSubscriptionController.cs, src/Presentation/Nop.Web/Administration/Models/Messages/NewsLetterSubscriptionListModel.cs, src/Presentation/Nop.Web/Administration/Views/NewsLetterSubscription/List.cshtml, src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml, upgradescripts/3.70-the next version/upgrade.sql
Added date filtering (start/end date) to the newsletter subscribers admin page.
=> #1362 Added date filtering to newsletter subscribers.

src/Presentation/Nop.Web.Framework/HtmlExtensions.cs
Useful for Bootstrap and other grid layout based CSS frameworks.
=> Option to wrap DatePickerDropDowns selects with span tags for styling

src/Libraries/Nop.Services/Security/EncryptionService.cs, src/Libraries/Nop.Services/Seo/SeoExtensions.cs, src/Plugins/Nop.Plugin.Shipping.UPS/UPSComputationMethod.cs, src/Plugins/Nop.Plugin.Shipping.USPS/USPSComputationMethod.cs
Currently this pull request has been sitting open for months https://github.com/nopSolutions/nopCommerce/pull/1300 please accept this one instead.
=> Switch to static encodings.

src/Libraries/Nop.Core/MimeTypes.cs, src/Presentation/Nop.Web/Administration/Controllers/CategoryController.cs, src/Presentation/Nop.Web/Administration/Controllers/CustomerController.cs, src/Presentation/Nop.Web/Administration/Controllers/ManufacturerController.cs, src/Presentation/Nop.Web/Administration/Controllers/OrderController.cs, src/Presentation/Nop.Web/Administration/Controllers/ProductController.cs
@schulz3000 is correct the MimeType for Xlsx should be "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" this fix targets #1284
=> Use the correct mime type for Xlsx.

src/Presentation/Nop.Web/Scripts/admin.navigation.js, src/Presentation/Nop.Web/Scripts/admin.search.js
=> #1142 fix for search functionality in admin area

src/Presentation/Nop.Web.Framework/UI/IPageHeadBuilder.cs, src/Presentation/Nop.Web.Framework/UI/LayoutExtensions.cs, src/Presentation/Nop.Web.Framework/UI/PageHeadBuilder.cs
Add support "async" attribute when are not bundled and bundling is disabled, added new bool parameter **isAsync**
=> Performance. Add support for "async" for javascript files

src/Tests/Nop.Services.Tests/Affiliates/AffiliateExtensionsTest.cs, src/Tests/Nop.Services.Tests/Affiliates/AffiliateServiceTest.cs, src/Tests/Nop.Services.Tests/Catalog/BackInStockSubscriptionServiceTest.cs, src/Tests/Nop.Services.Tests/Catalog/PriceCalculationServiceTests.cs, src/Tests/Nop.Services.Tests/Nop.Services.Tests.csproj
- Two new unit tests with 4 test cases each for `PriceCalculationServiceTests`.
- Addition  of test classes and methods for `AffiliateService `and `BackInStockSubscriptionService`.
=> Creation of new unit tests

src/Presentation/Nop.Web/Views/Checkout/Confirm.cshtml
Added a script to prevent double click on checkout confirm.
=> #1456 Prevent double click on confirm.

src/Presentation/Nop.Web.Framework/Menu/SiteMapNode.cs, src/Presentation/Nop.Web.Framework/Menu/XmlSiteMap.cs, src/Presentation/Nop.Web/Administration/Views/Shared/Menu.cshtml, src/Presentation/Nop.Web/Administration/sitemap.config
#2022 A new field called OpenUrlInNewTab is added in SiteMapNode.cs file which allow to configure particular URL to open in new tab through sitemap.config file. @AndreiMaz Please review the PR.
=> #2022 Admin section links for help are opened in new tab.

src/Presentation/Nop.Web/Administration/Views/Product/_CreateOrUpdate.Info.cshtml
#2036 Missing closing </td> element is added in "Administration/Views/Product/_CreateOrUpdate.Info.cshtml" view. @AndreiMaz please review the PR.
=> #2036 Missing closing </td> element is added.

src/Presentation/Nop.Web.Framework/Controllers/BaseController.cs, src/Presentation/Nop.Web.Framework/UI/NotifyType.cs, src/Presentation/Nop.Web/Administration/Views/Shared/Notifications.cshtml, src/Presentation/Nop.Web/Scripts/public.common.js, src/Presentation/Nop.Web/Themes/DefaultClean/Content/css/styles.css, src/Presentation/Nop.Web/Themes/DefaultClean/Content/css/styles.rtl.css, src/Presentation/Nop.Web/Views/Shared/_Notifications.cshtml
Implemented support for warning notifications. For both front- and back-end.
See issue:
https://github.com/nopSolutions/nopCommerce/issues/1558
=> Fix issue 1558 - Admin area. Add warning notification

src/Libraries/Nop.Core/Plugins/PluginManager.cs
simple minor fix in PluginManager Initialize method.
=> Minorfix of argument null check in pluginmanager

src/Presentation/Nop.Web/App_Data/Localization/Installation/installation.zhs.xml
_信心 (Xin Xin)_ means _confidence_ while _information_ means _信息 (Xin Xi)_.
=> Fix Chinese typo: 信心 -> 信息

src/Presentation/Nop.Web.Framework/Events/EventPublisherExtensions.cs, src/Presentation/Nop.Web.Framework/Events/ModelPrepared.cs, src/Presentation/Nop.Web.Framework/Events/ModelReceived.cs
re: [issue 282](https://github.com/nopSolutions/nopCommerce/issues/282) extended event publisher in Nop.Web.Framework to expose view models
=> extended event publisher in Nop.Web.Framework to expose view models

src/Presentation/Nop.Web/Controllers/ReturnRequestController.cs
if ReturnRequestsEnabled = true and ReturnRequestsAllowFiles = False
See #2592
=> #2592 Prevent uploading files

src/Libraries/Nop.Data/Mapping/Shipping/DeliveryDateMap.cs, src/Libraries/Nop.Data/Mapping/Shipping/ProductAvailabilityRangeMap.cs, src/Libraries/Nop.Data/Mapping/Shipping/ShippingMethodMap.cs, src/Libraries/Nop.Data/Mapping/Shipping/WarehouseMap.cs, src/Libraries/Nop.Data/Mapping/Tax/TaxCategoryMap.cs, src/Libraries/Nop.Data/Mapping/Topics/TopicMap.cs
=> #2745 Added missing "partial" keyword

src/Presentation/Nop.Web/Views/Customer/Register.cshtml
For languages other than English, the date of birth will be displayed in the local registration form.
=> update Register view - add localize labels for birth day

src/Presentation/Nop.Web/Views/Customer/Info.cshtml
For languages other than English, the date of birth will be displayed in the local info customer form.
=> update Info view - add localize for birth day

src/Plugins/Nop.Plugin.DiscountRules.CustomerRoles/Notes.txt, src/Plugins/Nop.Plugin.ExchangeRate.EcbExchange/Notes.txt, src/Plugins/Nop.Plugin.ExternalAuth.Facebook/Notes.txt, src/Plugins/Nop.Plugin.Payments.CheckMoneyOrder/Notes.txt, src/Plugins/Nop.Plugin.Payments.Manual/Notes.txt, src/Plugins/Nop.Plugin.Payments.PayPalStandard/Notes.txt, src/Plugins/Nop.Plugin.Payments.Square/Notes.txt, src/Plugins/Nop.Plugin.Payments.Worldpay/Notes.txt, src/Plugins/Nop.Plugin.Pickup.PickupInStore/Notes.txt, src/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Notes.txt, src/Plugins/Nop.Plugin.Shipping.UPS/Notes.txt, src/Plugins/Nop.Plugin.Tax.FixedOrByCountryStateZip/Notes.txt, src/Plugins/Nop.Plugin.Widgets.GoogleAnalytics/Notes.txt, src/Plugins/Nop.Plugin.Widgets.NivoSlider/Notes.txt
Target framework property is updated from **net461** to **netcoreapp2.1** in all plugins Notes.txt file.
Resolves: #3065
@AndreiMaz Please review the pull request
=> Target framework is updated in all Notes.txt file #3065

src/Presentation/Nop.Web.Framework/UI/Paging/Pager.cs
Paging css classes occur big problem for integrate some html templates. But accomplish if we make changes css class names.
=> Add paging css class names as fields

src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs
Use cookie-based TempData provider (useful in webfarm)
Update ServiceCollectionExtensions.cs
nopSolutions#2998
and part of,
nopSolutions#2494
=> Use cookie-based TempData provider (useful in webfarm)

src/Presentation/Nop.Web/App_Data/Localization/Installation/installation.pt-br.xml
changed some wrong words in portuguese (Brazil) to their correct words.
=> word corrections - portuguese (Brazil)

src/Presentation/Nop.Web/Areas/Admin/Factories/OrderModelFactory.cs
https://github.com/nopSolutions/nopCommerce/issues/3444
=> Fixed duplicated default select option under country drop-down 

src/Libraries/Nop.Core/Caching/PerRequestCacheManager.cs
Here is a better fix for 3529 which uses the ReaderWriterLockSlim as recommended by @skoshelev
=> Fix for 3529 - Update PerRequestCacheManager.cs

src/Libraries/Nop.Core/Caching/PerRequestCacheManager.cs
Please see my prior PR for an explanation of why this is needed. PR #3542
=> Fix for Regression introduced by PR 3537 - Second Attempt

src/Libraries/Nop.Services/Helpers/BrowscapXmlParser.cs
#3608 Improved IsCrawler performance by combining all useragent regexes. This change was suggested by @soci1248 here https://github.com/nopSolutions/nopCommerce/issues/3475#issuecomment-468414760 and tested by @fpdavis here https://github.com/nopSolutions/nopCommerce/issues/3475#issuecomment-469768413 in issue #3475.
=> #3608 Combined crawler regex

src/Presentation/Nop.Web.Framework/Security/FilePermissionHelper.cs
Added Mac OSX specific permissions check as suggested by @bzass in #3736
=> #3736 Bugs/rudgr/3736 installation fails when run on mac

src/Presentation/Nop.Web/App_Data/Localization/Installation/installation.ko-kr.xml
There are other language installation pages, but I don't see Korean.
So I added a Korean page.
Added Korean language pack for installation
=> Added Korean language pack for installation

src/Libraries/Nop.Core/Domain/Catalog/CatalogSettings.cs, src/Libraries/Nop.Services/Installation/CodeFirstInstallationService.cs, src/Presentation/Nop.Web/Areas/Admin/Infrastructure/Mapper/AdminMapperConfiguration.cs, src/Presentation/Nop.Web/Controllers/ProductController.cs
=> Adds setting to change child product redirect code

src/Presentation/Nop.Web/Areas/Admin/Controllers/OrderController.cs
Parsing item quantity (Line 2214) repeated code removed
=> AddShipment repeated code removed

src/Libraries/Nop.Services/Shipping/IShipmentService.cs, src/Libraries/Nop.Services/Shipping/ShipmentService.cs, src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml, src/Presentation/Nop.Web/Areas/Admin/Factories/OrderModelFactory.cs, src/Presentation/Nop.Web/Areas/Admin/Models/Orders/ShipmentSearchModel.cs, src/Presentation/Nop.Web/Areas/Admin/Views/Order/ShipmentList.cshtml, upgradescripts/4.20-4.30 (under development)/upgrade.sql
Kindly verify code.
Language Resource added to SQL upgrade file & Default Resource xml file too
#4065
=> Filter option available for shipment not delivered #4065

src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs
Small update to fix top menu navigation to respect DisplayOrder property of the category
Issue Reference: #4134
=> Update to top menu navigation to respect the DisplayOrder property

src/Libraries/Nop.Services/Catalog/IManufacturerService.cs, src/Libraries/Nop.Services/Catalog/ManufacturerService.cs, src/Presentation/Nop.Web/Areas/Admin/Controllers/ManufacturerController.cs, src/Presentation/Nop.Web/Areas/Admin/Views/Manufacturer/List.cshtml
#4112
Added on manufacturers page
=> Manufacturers - Add master checkbox and Delete Selected button

src/Libraries/Nop.Services/Catalog/IProductTagService.cs, src/Libraries/Nop.Services/Catalog/ProductTagService.cs, src/Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs, src/Presentation/Nop.Web/Areas/Admin/Views/Product/ProductTags.cshtml
#4112
Added on product tags page
=> Product Tags - Add master checkbox and delete selected button

src/Libraries/Nop.Services/Catalog/CategoryService.cs, src/Libraries/Nop.Services/Catalog/ICategoryService.cs, src/Presentation/Nop.Web/Areas/Admin/Controllers/CategoryController.cs, src/Presentation/Nop.Web/Areas/Admin/Views/Category/List.cshtml
https://github.com/nopSolutions/nopCommerce/issues/4112
Added on categories page
=> Categories - Add master checkbox and Delete Selected button

src/Presentation/Nop.Web/Views/Shared/Components/HeaderLinks/Default.cshtml
fix: https://github.com/nopSolutions/nopCommerce/issues/4181
=> Fix Register route inside the login page

src/Libraries/Nop.Services/Catalog/ISpecificationAttributeService.cs, src/Libraries/Nop.Services/Catalog/SpecificationAttributeService.cs, src/Presentation/Nop.Web/Areas/Admin/Controllers/SpecificationAttributeController.cs, src/Presentation/Nop.Web/Areas/Admin/Views/SpecificationAttribute/List.cshtml
=> Specification Attributes - Add master checkbox and Delete selected button

src/Libraries/Nop.Services/Orders/CheckoutAttributeService.cs, src/Libraries/Nop.Services/Orders/ICheckoutAttributeService.cs, src/Presentation/Nop.Web/Areas/Admin/Controllers/CheckoutAttributeController.cs, src/Presentation/Nop.Web/Areas/Admin/Views/CheckoutAttribute/List.cshtml
=> Checkout Attributes - Add master checkbox and delete selected button

src/Presentation/Nop.Web.Framework/UI/PageHeadBuilder.cs
=> bundle minification using AbsolutePath for cross platform

src/Libraries/Nop.Core/Domain/Common/GenericAttribute.cs, src/Libraries/Nop.Services/Common/GenericAttributeService.cs, src/Tests/Nop.Services.Tests/Common/GenericAttributeServiceTests.cs, upgradescripts/4.20-4.30 (under development)/upgrade.sql
https://github.com/nopSolutions/nopCommerce/issues/4267
=> Add CreatedOrUpdatedDateUTC to the GenericAttribute entity

src/Libraries/Nop.Core/Infrastructure/NopEngine.cs, src/Presentation/Nop.Web.Framework/Models/BaseSearchModel.cs, src/Presentation/Nop.Web/Areas/Admin/Factories/CustomerModelFactory.cs, src/Presentation/Nop.Web/Areas/Admin/Infrastructure/Mapper/AdminMapperConfiguration.cs, src/Presentation/Nop.Web/Areas/Admin/Models/Customers/CustomerModel.cs, src/Presentation/Nop.Web/Areas/Admin/Views/Customer/_CreateOrUpdate.Info.cshtml, src/Tests/Nop.Web.MVC.Tests/Admin/Factories/CustomerModelFactoryTests.cs
https://github.com/nopSolutions/nopCommerce/issues/4261
=> Hide 'Registered in the Store' label if there is only one store

src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml, src/Presentation/Nop.Web/Views/Catalog/Search.cshtml, src/Presentation/Nop.Web/Views/Customer/Register.cshtml, src/Presentation/Nop.Web/Views/Product/_AddToCart.cshtml, src/Presentation/Nop.Web/Views/Product/_ProductPrice.cshtml
Change 1: added changes for quantity on product page for aria lable to comply with ADA
added aria-label for product quantity on both classes: qty-dropdown and qty-input   (_AddToCart.cshtml).
Added Locals for AriaLabel for Product.Qty.AriaLabel    (defaultResources.nopres.xml). 
<LocaleResource Name="Products.Qty.AriaLabel">
<Value>Enter a quantity</Value>
</LocaleResource>
Change 2: Add property for label using Id and that Id to price span  (_ProductPrice.cshtml)
Change 3: Added for on label using Id from span that also need to include a Id on Search page and the same was done on Register page
Added Label with Id for gender within (Register.cshtml):
Added label with Id for price range within (Search.cshtml):
=> Modified labels to use Id and included Aria-labels to comply with ADA

src/Libraries/Nop.Core/Domain/Catalog/CatalogSettings.cs, src/Libraries/Nop.Services/Installation/CodeFirstInstallationService.cs, src/Presentation/Nop.Web/App_Data/Install/Fast/create_required_data.sql, src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml, src/Presentation/Nop.Web/Areas/Admin/Controllers/SettingController.cs, src/Presentation/Nop.Web/Areas/Admin/Infrastructure/Mapper/AdminMapperConfiguration.cs, src/Presentation/Nop.Web/Areas/Admin/Models/Settings/CatalogSettingsModel.cs, src/Presentation/Nop.Web/Areas/Admin/Views/Setting/_Catalog.Search.cshtml, src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs, src/Presentation/Nop.Web/Models/Catalog/SearchBoxModel.cs, src/Presentation/Nop.Web/Views/Shared/Components/SearchBox/Default.cshtml
I submitted issue 4086 requesting the ability to hide the search box...this is the code implementing that feature.  Someone else out there might want to hide the search box too.
=> Implemented issue/feature 4086 - Ability to hide the search box

src/Presentation/Nop.Web/App_Data/Install/MySQL/StoredProcedures.sql
- fixed db objects casing
- added replication-related declarations to sprocs definitions
=> fixes in mysql/StoredProcedures.sql to make it work correctly on mysql 8.0

src/Libraries/Nop.Services/Catalog/ProductService.cs
LowStockReports bugfix on product attribute combinations
=> Bugfix ProductService.cs

src/Libraries/Nop.Services/Localization/LocalizationService.cs
=> Fixed issue to import(insert) and reimport(update) a language file

src/Presentation/Nop.Web/Areas/Admin/Views/Setting/AllSettings.cshtml
Corrected the reset of the fields. For the store field, I have just set the selection to the first value.
=> Fix #4415 for display of the default store after creation of setting

src/Presentation/Nop.Web/Areas/Admin/Views/Manufacturer/List.cshtml
solution analyzer says Unmatched closing tag, so i removed it.
=> Fix issue Unmatched closing tag

src/Presentation/Nop.Web/App_Data/Localization/Installation/installation.zhs.xml
1.I  fixed some Simplified Chinese localization texts.
2.I carefully compared each line to make sure there was no mistake.
=> #4477 Fix some Simplified Chinese texts.

src/Presentation/Nop.Web/Areas/Admin/Views/Shared/_GridLocalization.cshtml, src/Presentation/Nop.Web/wwwroot/css/admin/styles.rtl.css
=> #4754 Fix Dashboard report CSS-styles for RTL version

src/Libraries/Nop.Services/Catalog/ProductService.cs, src/Tests/Nop.Services.Tests/Catalog/ProductServiceTests.cs
Fixes issue #4830 : ProductService.ProductIsAvailable not working correctly when dateTime argument not specified
=> fix issue 4830

src/Presentation/Nop.Web/Infrastructure/BaseRouteProvider.cs, src/Presentation/Nop.Web/Infrastructure/GenericUrlRouteProvider.cs, src/Presentation/Nop.Web/Infrastructure/RouteProvider.cs
Extract getting "lang pattern" into separate function to avoid code duplication
#4927
=> Fixed issue 4927

src/Libraries/Nop.Services/Orders/ReturnRequestService.cs
https://github.com/nopSolutions/nopCommerce/issues/4951
=> virtual keyword missing in ReturnRequestService 

src/Plugins/Nop.Plugin.Misc.SendinBlue/Views/Configure.cshtml
=> PR: Add UTM links

src/Libraries/Nop.Services/Installation/CodeFirstInstallationService.cs
=> Fix couple typos

src/Libraries/Nop.Services/Directory/CountryService.cs, src/Libraries/Nop.Services/Directory/NopDirectoryDefaults.cs
Hi, this PR fix the reported bug #4992
Thanks!
=> GetAllCountries cache by store

src/Presentation/Nop.Web/Views/Shared/Components/SocialButtons/Default.cshtml
Tested w/ **Lighthouse**. 
#4961
=> Unsafe Cross-Origin Links #4961

src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml
Fix of #5015, I've re-create the PR to squash to 1 commit & clean-up changes from my other PRs
=> Fix typo in resources

src/Libraries/Nop.Core/Domain/Common/SitemapCreatedEvent.cs, src/Libraries/Nop.Services/Seo/SitemapGenerator.cs
=> Add event when sitemap created #5043

src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml, src/Presentation/Nop.Web/Areas/Admin/Views/Log/List.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Log/View.cshtml
=> Add links to List & Details pages of LogController.

src/Libraries/Nop.Services/Orders/OrderTotalCalculationService.cs
=> Fixes the number of reward points to be calculated incorrectly

src/Libraries/Nop.Services/Orders/ShoppingCartService.cs
=> Fix for being able to edit required products in Shopping Cart

src/Libraries/Nop.Data/DataProviders/BaseDataProvider.cs, src/Libraries/Nop.Data/Mapping/FluentMigratorMetadataReader.cs, src/Libraries/Nop.Data/Mapping/NopEntityDescriptor.cs
After upgrading from v4.40 to v4.50 cannot access data in schemas other than dbo (#6139)
=> #6139 Fix for db schemas after 4.50.0 update

src/Presentation/Nop.Web.Framework/Infrastructure/PublicWidgetZones.cs, src/Presentation/Nop.Web/Views/Customer/Login.cshtml, src/Presentation/Nop.Web/Views/Customer/Register.cshtml, src/Presentation/Nop.Web/Views/Shared/_OrderReviewData.cshtml, src/Presentation/Nop.Web/Views/ShoppingCart/Wishlist.cshtml
Added additional WidgetZones for Login, Register, Wishlist and _OrderReviewData
=> Add WidgetZones

src/Presentation/Nop.Web.Framework/Migrations/UpgradeTo460/LocalizationMigration.cs, src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml, src/Presentation/Nop.Web/Controllers/CustomerController.cs
=> issue #6062 resolved  - Successful message in account detail & addresses

src/Libraries/Nop.Services/ExportImport/ImportManager.cs
=> Back In Stock Notification on Excel Import

src/Presentation/Nop.Web/Views/Catalog/_CatalogSelectors.cshtml
Added the attributes mentioned in the issue to the anchor tags.  Is it possible for this to be added to next minor release 45.0.3?
=> add ada attributes to anchor tag

src/Libraries/Nop.Services/Plugins/IUploadService.cs, src/Libraries/Nop.Services/Plugins/UploadService.cs, src/Presentation/Nop.Web/Areas/Admin/Controllers/PluginController.cs, src/Presentation/Nop.Web/Areas/Admin/Controllers/SettingController.cs
Changed following methods of IUploadService to async:
- UploadPluginsAndThemes
- UploadIconsArchive
- UploadFavicon
Solves issue #5254
=> Issue 5254 Use async methods in IUploadService

src/Presentation/Nop.Web/Areas/Admin/Controllers/HomeController.cs
Fixed typo https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Areas/Admin/Controllers/HomeController.cs#L81
=> #6261 Fixed typo

src/Tests/Nop.Tests/Nop.Web.Tests/Public/Factories/CommonModelFactoryTests.cs
Replace "\r\n" with Environment.NewLine on test case.
=> Fixes #6370

src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml, src/Presentation/Nop.Web/Areas/Admin/Controllers/CustomerController.cs
This is the pull request for the issue reported [here](https://github.com/nopSolutions/nopCommerce/issues/6336)
=> fix issue 6336: point validity exception issue

src/Tests/Nop.Tests/BaseNopTest.cs
Hi, the CommonFactoryModelTests was not working in the UnitTest project.  
The reason for this error is in the image below. I fixed.
=> Fixed CommonModelFactoryTests

README.md
Hi, the demo url should be <https://demo.nopcommerce.com/>
=> fix(demo): the demo url mismatch

src/Libraries/Nop.Services/Installation/InstallationService.cs
Disable date of birth by default in installation service, this pull request to fix #6522
=> Disable date of birth by default

src/Libraries/Nop.Services/Orders/IOrderProcessingService.cs, src/Libraries/Nop.Services/Orders/OrderProcessingService.cs, src/Presentation/Nop.Web.Framework/Migrations/UpgradeTo470/LocalizationMigration.cs, src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml, src/Presentation/Nop.Web/Controllers/OrderController.cs
This is the feature requested in #6309 
Of course, I'm happy to make any changes as needed :)
Screenshot of warning:
=> Notification when reordering unpublished products

src/Libraries/Nop.Core/Caching/DistributedCacheLocker.cs
- Don't pass the cancellation token to _distributedCache.RemoveAsync, as it may be in a cancelled state already and we want to remove the key regardless (the tests pass anyway because they use the memory distributed cache, which likely ignores the token)
- Now that we're using a synchronous callback, it is guaranteed to have finished executing when Timer.DisposeAsync has been called (note that the regular parameterless Dispose has no such guarantee), so we don't need the heartbeat token anymore
=> Don't pass token to remove in DistributedCacheLocker

src/Libraries/Nop.Services/Topics/ITopicService.cs, src/Libraries/Nop.Services/Topics/ITopicTemplateService.cs, src/Libraries/Nop.Services/Topics/TopicService.cs, src/Libraries/Nop.Services/Topics/TopicTemplateService.cs, src/Presentation/Nop.Web/Areas/Admin/Factories/ITemplateModelFactory.cs, src/Presentation/Nop.Web/Areas/Admin/Factories/ITopicModelFactory.cs, src/Presentation/Nop.Web/Areas/Admin/Factories/TemplateModelFactory.cs, src/Presentation/Nop.Web/Areas/Admin/Factories/TopicModelFactory.cs, src/Presentation/Nop.Web/Factories/ForumModelFactory.cs, src/Presentation/Nop.Web/Factories/IForumModelFactory.cs, src/Presentation/Nop.Web/Factories/ITopicModelFactory.cs, src/Presentation/Nop.Web/Factories/TopicModelFactory.cs
Correction of the word [**_topic_**], which is typed as [**_opic_**] in most methods summary.
=> typo fix for Topic

src/Libraries/Nop.Data/EntityRepository.cs, src/Libraries/Nop.Services/Catalog/ProductService.cs
I removed some unnecessary eager evaluations and turned for loops into pipelines to save execution time and memory, and changed lists into sets or dictionaries to avoid $O(n)$ lookups and make the code more intuitive.
Best regards,
Majako [majako.net](https://www.majako.net/)
=> Optimise and streamline EntityRepository and ProductService

src/Presentation/Nop.Web/Areas/Admin/Views/Order/List.cshtml
Add customer name to order list view in admin
=> issue #6702

src/Libraries/Nop.Services/Customers/CustomerService.cs
=> removed the UpdateCustomerAsync from the ResetCheckoutDataAsync method

src/Libraries/Nop.Services/Catalog/PriceCalculationService.cs
Fixes issue #6785 - Renamed "Gungarian Forint" to "Hungarian Forint".
=> Issue #6785 - Fixed a typo

src/Libraries/Nop.Services/Orders/ShoppingCartService.cs
Should say "standard" (with a d at the end)
=> Fix typo in "standart" in ShoppingCartService

Dockerfile
=> Fix icu-data issue on alpine >= 3.16.0

src/Libraries/Nop.Data/Migrations/Installation/Indexes.cs, src/Libraries/Nop.Data/Migrations/UpgradeTo470/AddIndexesMigration.cs, src/Libraries/Nop.Data/Migrations/UpgradeTo470/SchemaMigration.cs
Add indexes on Customer Id foreign key constraints
=> #6906 Add indexes on foreign key constraints

src/Libraries/Nop.Data/Migrations/Installation/Indexes.cs, src/Libraries/Nop.Data/Migrations/UpgradeTo470/AddIndexesMigration.cs
Hi this closes [https://github.com/nopSolutions/nopCommerce/issues/6940](https://github.com/nopSolutions/nopCommerce/issues/6940)
=> Add database index for product.name Forums_Topic.Subject

src/Plugins/Nop.Plugin.Payments.CyberSource/Views/Configure.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Currency/_CreateOrUpdate.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Customer/_CreateOrUpdate.RewardPoints.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Discount/_CreateOrUpdate.Info.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/MessageTemplate/_CreateOrUpdate.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Order/_OrderDetails.Info.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Product/ProductSpecAttributeAddOrEdit.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.DownloadableProduct.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.GiftCard.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.Info.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.Inventory.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.Recurring.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.Rental.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdateProductAttributeMapping.Info.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdateProductAttributeValue.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/_CreateOrUpdate.Info.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/_CreateOrUpdate.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Setting/_CustomerUser.Account.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Setting/_CustomerUser.Common.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Setting/_CustomerUser.Security.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/Setting/_RewardPoints.EarningRewardPoints.cshtml, src/Presentation/Nop.Web/Views/Checkout/_PickupPoints.cshtml
Hi  @AndreiMaz  this change will close this [issue](https://github.com/nopSolutions/nopCommerce/issues/6969) and @exileDev partially related to [this](https://github.com/nopSolutions/nopCommerce/issues/6719#issuecomment-1591001379)
=> Fix @await syntax in cshtml files

src/Presentation/Nop.Web/Controllers/CatalogController.cs
Returning false if Manufacturer do not exist.
=> #7006 - Fixed error when Manufacturer is null

src/Libraries/Nop.Services/Orders/ShoppingCartService.cs
…issue https://github.com/nopSolutions/nopCommerce/issues/7101
=> Fixing deleted attribute adding shopping cart.

src/Libraries/Nop.Data/DataProviders/BaseDataProvider.cs, src/Libraries/Nop.Data/Mapping/NopMappingSchema.cs
=> Fixed mapping schema issues with database provider

src/Libraries/Nop.Core/Domain/Security/SecuritySettings.cs, src/Presentation/Nop.Web.Framework/Migrations/UpgradeTo470/SettingMigration.cs, src/Presentation/Nop.Web.Framework/Mvc/Filters/ValidateHoneypotAttribute.cs
- Added new `LogHoneypotDetection` security setting
- Updated 470 migration to set `LogHoneypotDetection` to `true` to maintain current behaviour of logs
- Updated bot detection logging
Resolves #7053
=> Issue #7053 honeypot detection log setting

src/Libraries/Nop.Data/Nop.Data.csproj
=> Upgrade Npgsql for CVE-2024-32655 security patch

src/Libraries/Nop.Services/Catalog/CopyProductService.cs
Fixed the issue with StockQuantityHistory for product attribute combinations when copying a product with combinations. Resolves issue #7202.
=> Fixed the issue with StockQuantityHistory for product attribute combinations when copying a product with combinations. Resolves issue #7202.

src/Presentation/Nop.Web/App_Data/Localization/states.txt
Nepal's constitution has these new names of the states assigned
=> Updated the province name of Nepal as per new naming

src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs
This pull request addresses issue #7289 where the `PictureModel` property in `VendorModel` was not being set in the `PrepareVendorModelAsync` method. With this update, `PictureModel` is now properly set, ensuring that vendor pictures are available and not null on pages like `Views/Catalog/Vendor.cshtml`.
**Changes Made:**
- Updated the `PrepareVendorModelAsync` method to set the `PictureModel` within `VendorModel`.
- Ensured that `PictureModel` is no longer null and accessible for display on relevant pages.
**nopCommerce version:**
4.70
Steps to reproduce the problem:
In VendorModel, there is a PictureModel property; however, it is not being set in the PrepareVendorModelAsync method. As a result, when users attempt to use the vendor's picture on pages like `Views/Catalog/Vendor.cshtml`, …
=> Set `PictureModel` in `PrepareVendorModelAsync` method

src/Presentation/Nop.Web/Areas/Admin/Views/Shared/Table.cshtml
Adding the form-control class to these inputs helps nop admin dashboard fields better conform to dashboard styles.
=> add class form-control Table.cshtml text/number inputs

src/Libraries/Nop.Data/DataProviders/BaseDataProvider.cs, src/Tests/Nop.Tests/SqLiteNopDataProvider.cs
Fixes #7369
Set KeepIdentity option true in BulkCopyOptions
=> Set KeepIdentity option true in BulkCopyOptions

src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs
fixes #7453 
currently loads parent category picture.
Fixes reference so that child category picture is loaded instead of parent.
=> fix 7453 Update CatalogModelFactory.cs

src/Libraries/Nop.Services/Catalog/CategoryService.cs, src/Libraries/Nop.Services/Catalog/ManufacturerService.cs
Replaced the explicit foreach loop with a LINQ `FirstOrDefault` for improved readability while preserving functionality.
=> Refactor ProductCategory and ProductManufacturer Search with LINQ for Improved Code Readability

src/Libraries/Nop.Services/Orders/RewardPointService.cs
Refactored query executions in `RewardPointService` to use asynchronous operations (`ToListAsync`) instead of synchronous calls (`ToList`). This improves performance when processing reward points.
=> Optimize Reward Points Queries with Asynchronous Execution

src/Libraries/Nop.Services/Catalog/ProductService.cs
Updated ReserveInventoryAsync to use ToListAsync() for fetching product inventory, ensuring non-blocking database calls.
=> Enhance Inventory Reservation with Asynchronous Query

src/Libraries/Nop.Services/Orders/ShoppingCartService.cs
Refactored the `IsCustomerShoppingCartEmpty` method in `ShoppingCartService` to use `AnyAsync` for async database query execution
=> IsCustomerShoppingCartEmpty method in ShoppingCartService with async database query execution

src/Libraries/Nop.Services/Security/AclService.cs
Updated `IsEntityAclMappingExistAsync` method to use query.AnyAsync for improved async query execution.
=> Refactor IsEntityAclMappingExistAsync for Async Query Execution

src/Libraries/Nop.Services/ExportImport/ImportManager.cs
Fix the method SplitProductFile in ImportManager.
=> 7529 - Infinite recursion in product import

src/Libraries/Nop.Services/Localization/LanguageService.cs
=> Unnecessary comment removed

src/Presentation/Nop.Web.Framework/Menu/AdminMenu.cs, src/Presentation/Nop.Web.Framework/Menu/AdminMenuItem.cs
- Method renamed
- Used latest syntax
=> Rename AdminMenu.GetItemBySystem to AdminMenu.GetItemBySystemName

src/Libraries/Nop.Services/Catalog/ProductAttributeService.cs
Replaced the deletion in loop with a bulk delete operation to improve performance. This reduces the number of database calls.
Other changes is for improve code readability.
=> Optimize DeleteProductAttributesAsync by using bulk delete

src/Presentation/Nop.Web/Areas/Admin/Views/Customer/_CreateOrUpdate.cshtml, src/Presentation/Nop.Web/Areas/Admin/Views/_ViewImports.cshtml
Checking permission before rendering
=> Render "Orders", "Activity Log" and "Impersonation" blocks on the customer edit page based on the associated permission

src/Libraries/Nop.Core/Domain/Catalog/PostCopyProductEvent.cs, src/Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs
new post copy product event added with the new product and the original product.
=> Add new PostCopyProductEvent event

src/Libraries/Nop.Services/Messages/WorkflowMessageService.cs, src/Presentation/Nop.Web/Areas/Admin/Views/Order/AddShipment.cshtml, src/Presentation/Nop.Web/Views/Catalog/Search.cshtml
Removed unnecessary duplicate code
=> Unnecessary duplicate code remove
