nopSolutions/nopCommerce

src/Libraries/Nop.Core/Fakes/FakeHttpContext.cs

Changed _items Instance from Dictionary to Hashtable like in Original
Implementation
(http://referencesource.microsoft.com/#System.Web/HttpContext.cs,a38a77eb7b62f64d,references)
I think it's not useful to change FakeHttpContext Items to
ConcurrentDictionary because default HttpContext also not use it and you
can run into same behavior like described in the issue with async calls
in default HttpContext.
Partialy solve #986

Change FakeHttpContext->Items to Hashtable

---

src/Libraries/Nop.Core/Plugins/PluginExtensions.cs

This pull requests add's support for additional image formats for plugin logos. Specifically image formats that support transparency because a logo may appear on a background a  colored background.

Add support for plugin logos with transparent backgrounds.

---

src/Presentation/Nop.Web/Administration/Infrastructure/Mapper/AutoMapperConfiguration.cs

Added missing properties from Automapper configuration. The test `AutoMapperConfigurationTest.Configuration_is_valid()` was failing because of these missing mapped properties.

Automapper configuration - added missing properties (ignored)

---

src/Libraries/Nop.Services/Tasks/Task.cs

Set LastSuccessUtc property to the database value in the constructor as well. Without it, if the task throws an exception, the LastSuccessUtc column in the database will be overwritten with NULL since the property is never initialized.

Set LastSuccessUtc in Task constructor

---

src/Presentation/Nop.Web/Views/Checkout/Confirm.cshtml
src/Presentation/Nop.Web/Views/Checkout/OpcConfirmOrder.cshtml
src/Presentation/Nop.Web/Views/ShoppingCart/OrderSummary.cshtml

Replace span with label with "for" attribute.

Fix: Terms of services. Checkbox labels should be clickable #1717

---

src/Presentation/Nop.Web/Administration/Controllers/CommonController.cs
src/Presentation/Nop.Web/Administration/Models/Common/SystemInfoModel.cs
src/Presentation/Nop.Web/Administration/Views/Common/SystemInfo.cshtml

As explained here: http://www.nopcommerce.com/boards/t/45058/show-more-assembly-information-in-the-system-information-page.aspx#178867
* Show server variables and assemblies in a proper list (with bullets)
* Show server variable name in bold letters
* Hide server variables with raw HTTP header information that is repeated below
* Show assembly name in bold letters
* Show if assembly is in debug/release mode
* If in full trust, show assembly location (is commented out but CommonHelper has a method to get Trust)
* If in full trust, show assembly build date (we find this information useful when diagnosing problems)

Show more detailed information of loaded assemblies

---

src/Plugins/Nop.Plugin.Widgets.NivoSlider/Infrastructure/Cache/ModelCacheEventConsumer.cs

#2397 Fixed cache key typo (nivosrlider -> nivoslider) in nivoslider plugin. Also removed the unused using statement **Nop.Core.Infrastructure**.
@AndreiMaz and @mariannk please review the pull request.

Fixed cache key typo in nivo slider plugin.

---

src/Tests/Nop.Core.Tests/WebHelperTests.cs

I don't think RemoveQueryString and ModifyQueryString should change anchor to lowercase, but some tests were failing because they were expecting anchor in lowercase.

ModifyQueryString and RemoveQueryString methods were failing in unit tests

---

src/Libraries/Nop.Services/Seo/SitemapGenerator.cs

Currently sitemap uses culture specific dates for generating modification dates of products, which leads to dates like "2561-01-29" for cultures which their default calendar is something other than gregorian calendar. This update fixes this issue in sitemaps' <lastmod> fields.

Update SitemapGenerator.cs to use gregorian date in sitemaps

---

src/Libraries/Nop.Core/Caching/ILocker.cs
src/Libraries/Nop.Core/Caching/IRedisConnectionWrapper.cs
src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs
src/Libraries/Nop.Core/Caching/RedisConnectionWrapper.cs
src/Libraries/Nop.Services/Tasks/Task.cs
src/Presentation/Nop.Web.Framework/Infrastructure/DependencyRegistrar.cs
src/Tests/Nop.Core.Tests/Caching/MemoryCacheManagerTests.cs

Closes #2930 
Rather than leave Redis-specific lock code, I introduced an `ILocker` interface with an in-memory implementation.
cc @skoshelev @AndreiMaz

Add In-Memory Scheduled Task Lock

---

src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml
src/Presentation/Nop.Web/Views/Catalog/_FilterSpecsBox.cshtml

Trailing space was used for formatting purpose in language resource "Filtering.SpecificationFilter.Separator". Also it seems that leading and trailing spaces are trimmed during editing of a language resource value.
The Formatting got corrected in \Presentation\Nop.Web\Views\Catalog\_FilterSpecsBox.cshtml file.

Add a formatting correction to _FilterSpecsBox.cshtml

---

src/Presentation/Nop.Web/Themes/DefaultClean/Content/css/styles.css
src/Presentation/Nop.Web/Themes/DefaultClean/Content/css/styles.rtl.css

Apply font family settings to button elements in styles.css and styles.rtl.css
Currently web browser's font settings take precedence.
Example: "Proceed to checkout" button on shopping cart page.

Apply font family settings to button elements

---

src/Plugins/Nop.Plugin.DiscountRules.CustomerRoles/Nop.Plugin.DiscountRules.CustomerRoles.csproj
src/Plugins/Nop.Plugin.DiscountRules.CustomerRoles/Notes.txt
src/Plugins/Nop.Plugin.ExchangeRate.EcbExchange/Nop.Plugin.ExchangeRate.EcbExchange.csproj
src/Plugins/Nop.Plugin.ExchangeRate.EcbExchange/Notes.txt
src/Plugins/Nop.Plugin.ExternalAuth.Facebook/Nop.Plugin.ExternalAuth.Facebook.csproj
src/Plugins/Nop.Plugin.ExternalAuth.Facebook/Notes.txt
src/Plugins/Nop.Plugin.Payments.CheckMoneyOrder/Nop.Plugin.Payments.CheckMoneyOrder.csproj
src/Plugins/Nop.Plugin.Payments.CheckMoneyOrder/Notes.txt
src/Plugins/Nop.Plugin.Payments.Manual/Nop.Plugin.Payments.Manual.csproj
src/Plugins/Nop.Plugin.Payments.Manual/Notes.txt
src/Plugins/Nop.Plugin.Payments.PayPalStandard/Nop.Plugin.Payments.PayPalStandard.csproj
src/Plugins/Nop.Plugin.Payments.PayPalStandard/Notes.txt
src/Plugins/Nop.Plugin.Payments.Square/Nop.Plugin.Payments.Square.csproj
src/Plugins/Nop.Plugin.Payments.Square/Notes.txt
src/Plugins/Nop.Plugin.Payments.Worldpay/Nop.Plugin.Payments.Worldpay.csproj
src/Plugins/Nop.Plugin.Payments.Worldpay/Notes.txt
src/Plugins/Nop.Plugin.Pickup.PickupInStore/Nop.Plugin.Pickup.PickupInStore.csproj
src/Plugins/Nop.Plugin.Pickup.PickupInStore/Notes.txt
src/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Nop.Plugin.Shipping.FixedByWeightByTotal.csproj
src/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Notes.txt
src/Plugins/Nop.Plugin.Shipping.UPS/Nop.Plugin.Shipping.UPS.csproj
src/Plugins/Nop.Plugin.Shipping.UPS/Notes.txt
src/Plugins/Nop.Plugin.Tax.FixedOrByCountryStateZip/Nop.Plugin.Tax.FixedOrByCountryStateZip.csproj
src/Plugins/Nop.Plugin.Tax.FixedOrByCountryStateZip/Notes.txt
src/Plugins/Nop.Plugin.Widgets.GoogleAnalytics/Nop.Plugin.Widgets.GoogleAnalytics.csproj
src/Plugins/Nop.Plugin.Widgets.GoogleAnalytics/Notes.txt
src/Plugins/Nop.Plugin.Widgets.NivoSlider/Nop.Plugin.Widgets.NivoSlider.csproj
src/Plugins/Nop.Plugin.Widgets.NivoSlider/Notes.txt

This is just a small cleanup of the plugin project files. Since `OutputPath` is the same for debug & release, it can be moved up to the shared property group instead of having it duplicated. Visual Studio understand this just fine in the new project system.

Small project file cleanup: move OutputPath to shared property group

---

src/Libraries/Nop.Services/Orders/ShoppingCartService.cs

For issue #3589. Extract the single shopping cart item equality comparison so it can be easily overridden by plugins.

Extract shopping cart item equality in ShoppingCartService

---

src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs

@AndreiMaz, @RomanovM, @skoshelev 
I haven't found any mentions and reasons why DbContext Pooling was avoided, so decided to add it.
The code change is very small and easy to roll back, but it can be very effective for performance and scaling.
Docs:
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#dbcontext-pooling

Add DbContext pooling

---

src/Presentation/Nop.Web/Controllers/BackInStockSubscriptionController.cs
src/Presentation/Nop.Web/Factories/ForumModelFactory.cs
src/Presentation/Nop.Web/Infrastructure/RouteProvider.cs

These commits fix the 4 route suggestions made in issue [3709](https://github.com/nopSolutions/nopCommerce/issues/3709).
As there are no unit tests for routes, I have gone through the changes to ensure that these routes still work as expected. Where routes have been removed, I have also gone through the code to find those removed route usages and point them to the correct route.

Issue 3709 RouteProvider refactorings

---

Dockerfile

To enable globalization support we need to add the icu-libs apk package to the runtime environment in the docker container. We also need the DOTNET_SYSTEM_GLOBALIZATION_INVARIANT variable set to false (default true in alpine runtime) to support globalization.

Issue 3813 - Support globalization in alpine runtime

---

src/Presentation/Nop.Web/wwwroot/css/admin/styles.rtl.css

[please visit this link to comprehend what is the exact issue](https://github.com/nopSolutions/nopCommerce/issues/4081)
The solution is removing this part of Css which really is not needed.
please lets see (chrome 77.x):
and also the firefox :

issue-4081-chrome-problem-for-RTL-languages

---

src/Libraries/Nop.Services/ExportImport/ExportManager.cs

When UsernamesEnabled, the registration form still asks for email. This means that the email is collected info regardless of UsernamesEnabled. The GDPR requires exporting *all* information related to the user, so this must also be exported regardless of the UsernamesEnabled setting.

Do not ignore email in GDPR when UsernamesEnabled

---

src/Libraries/Nop.Core/Configuration/NopConfig.cs
src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs
src/Presentation/Nop.Web.Framework/Nop.Web.Framework.csproj
src/Presentation/Nop.Web/appsettings.json

Resolves issue #4166 
This has been tested and we are running it in production.
This PR adds 3 appsettings.json settings:
**UseAzureBlobStorageToStoreDataProtectionKeys**
true/false: whether to store data protection keys in an Azure blob storage container
**AzureBlobStorageContainerNameForDataProtectionKeys**
The container name to store the data protection keys. The connection string used is AzureBlobStorageConnectionString but the data protection keys need to live in a private container separate from the media container.
**AzureKeyVaultIdForDataProtectionKeys**
Optional key vault ID. If non-empty, the key stored in the blob container is encrypted using this Azure Key Vault.

Allow DataProtectionKeys to be stored in Azure Blob Storage

---

src/Libraries/Nop.Core/Infrastructure/AppDomainTypeFinder.cs

The method DoesTypeImplementOpenGeneric now will check all implemented interfaces of given type, not only the first occurrence.

Hotfix: DoesTypeImplementOpenGeneric

---

src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ApplicationBuilderExtensions.cs

Simple fix. Allows download in the administration if backup directory is changed.

Use NopCommonDefaults.DbBackupsPath for static file provider

---

src/Plugins/Nop.Plugin.Payments.PayPalSmartPaymentButtons/Services/ServiceManager.cs

The current implementation uses toString("F") to convert money to string and send it to PayPal API. However, toString("F") gives 3 decimal places under some(if not all) culture settings resulting in rejection from PayPal API(only 2 decimal places is accepted).
So I think it is a good idea to enforce this 2 d.p. requirement by formatting it explicitly.
The fix followed other similar places in source code. For example, nopSolutions/nopCommerce:src/Plugins/Nop.Plugin.Payments.PayPalStandard/PayPalStandardPaymentProcessor.cs@develop#L283

Fix wrong decimal precision in Paypal Smart Button plugin

---

src/Libraries/Nop.Services/Seo/UrlRecordService.cs

Seo-friendly slug generation does not work as expected for a content which contains a specific Turkish character (capital i -> `İ`).

lowercase non-western char from the seo char table

---

src/Libraries/Nop.Services/Media/RoxyFileman/BaseRoxyFilemanService.cs

This is a possible solution for issue #4597 .
This change allows Roxy Fileman to display many types of media files.
Please take a look at this list of extensions - it was based on list of extension icons in Roxy js files and may be incomplete.
I've included video and audio files, because Roxy treats them all as Media type. You may want to remove audio extensions, because tinyMCE show these files in "Add Video" tab.

Issue 4597 handling videos

---

src/Libraries/Nop.Data/Migrations/MigrationManager.cs

There is no type mapping in MigrationManager.cs for long type.
A line should be added to _typeMapping :
[typeof(long)] = c => c.AsInt64(),
Source: https://www.nopcommerce.com/en/boards/topic/82849/43-missing-database-type-mapping-for-int64long

Add database type mapping for int64/long #4891

---

src/Libraries/Nop.Data/Mapping/FluentMigratorMetadataReader.cs

The dictionaries in the `FluentMigratorMetadataReader` are recreated for every call to the `GetAttribute` method, so the dictionary is completely ineffective.  This PR fixes the code to operate in its intended fashion.
This is because:
```csharp
public string Test => "hello";
```
is equivalent to:
```csharp
public string Test
{
get {
return "hello";
}
}
```
On the other hand, this:
```csharp
public string Test { get; } = "hello";
```
is equivalent to:
```csharp
private string _test = "hello";  // hidden field on the class, set during the constructor or static constructor
public string Test
{
get {
return _test;
}
}
```
Note that there are many other uses through the code of the `=>` operator for a static readonly property -- usually for `CacheKey` objects.  I'm guessing that all of these …

Fix FluentMigratorMetadataReader to enable dictionary use

---

src/Libraries/Nop.Services/Catalog/PriceCalculationService.cs

GetProductAttributeValuePriceAdjustment should use the passed in Customer instead of the _workContext.Customer. This method calls GetFinalPrice two ways (lines 469 and 484) but is not consistent. It should use the Customer parameter so it can be used in plugins to get the price adjustment for a specific customer.

Standardize customer use in GetProductAttributeValuePriceAdjustment

---

src/Presentation/Nop.Web/Views/Blog/List.cshtml

I don't see any reason why there should be a leading dash in front of the blog post date

remove unnecessary dash in front of blog post-date

---

src/Presentation/Nop.Web/Models/Catalog/ProductEmailAFriendModel.cs
src/Presentation/Nop.Web/Models/Install/InstallModel.cs

Added DataType Attributes to the 2 instances I could find of it being missing. 
I was unable to locate any instances of PhoneNumber attributes being missing.

Updated missing DataTypes on Email Fields

---

src/Presentation/Nop.Web/Areas/Admin/Views/Shipping/Methods.cshtml

This links back to the shipping rate computation method list instead of the plugin page.

Fixes #4821, adds 'back to' link for Shipping Methods page

---

src/Presentation/Nop.Web.Framework/WebWorkContext.cs

This allows using `_workContext.CurrentCustomer` from signal-r hub callbacks, which set their own headers. Without this check, an error is thrown that complains that headers have already been sent.

Check if headers are sent before setting cookie

---

src/Libraries/Nop.Services/Common/NopCommonDefaults.cs

#5178
Fix of: Incorrect formatting for strings in NopCommonDefaults.cs

Fix of: Incorrect formatting for strings in NopCommonDefaults.cs

---

src/Plugins/Nop.Plugin.Payments.PayPalStandard/Controllers/PaymentPayPalStandardController.cs

According to the PayPal documentation:
'payment_fee' is a deprecated field. Use 'mc_fee' instead.

Replace 'payment_fee' to 'mc_fee'

---

src/Libraries/Nop.Core/Domain/Customers/ExternalAuthenticationSettings.cs

Just correcting a minor typo for the MAML of the ActiveAuthenticationMethodSystemNames property. Let me know if this needs a better branch name as I just created this PR from the web UI.

Fixing typo in ExternalAuthenticationSettings.cs

---

src/Libraries/Nop.Services/Media/RoxyFileman/RoxyFilemanProvider.cs

If this needs to be a specific implementation of `INopFileProvider`, that specific implementation should be fetched instead of assuming the type returned from the IoC container.
The cast appears to be redundant as `GetVirtualPath(...)` and `GetDirectoryName(...)` are available on `INopFileProvider` anyways.

Removing redundant cast

---

src/Presentation/Nop.Web/Areas/Admin/Views/Shared/Table.cshtml

Recreated pull request as branch wasn't clean before requesting.
This fixes the main issue described in #5284 Admin Tables Footer not rendering on Child Table.
It does not however address the other issue relating to inline editing/deleting, which appears to be more complicated to rectify.

Fix for adding footer to Child DataTable

---

src/Libraries/Nop.Services/Orders/ShoppingCartService.cs

In a multi-store/single-store setup, we must rely on `storeId` param not `_storeContext.GetCurrentStoreAsync()`.

Fix store mapping authorization check on multi-store setups

---

src/Presentation/Nop.Web/Factories/OrderModelFactory.cs
src/Presentation/Nop.Web/Models/Order/OrderDetailsModel.cs

It would be very handy to get the decimal values of `OrderSubtotal`, `OrderTotal`, `OrderTotalDiscount` in [OrderDetailsModel](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Models/Order/OrderDetailsModel.cs). Also this is needed to include the values in the WebApi plugin models.

Add decimal values to OrderDetailsModel

---

src/Libraries/Nop.Services/Messages/MessageTokenProvider.cs

Fixes #3946 and #6033.
I don't know why this method is doing what it is doing nor what impact this change will have on the consuming services (ex: do any services expect the badly encoded URL that was previously provided). Feedback is appreciated. This fixes the email reset / activation issue but what other test cases need run?

Issues 3946 & 6033 - Fix URL encoding in RouteUrlAsync

---

Dockerfile

When building the web application container, ensure it uses the proper path from documentation so that mounted paths work as expected.
See [forum post](https://www.nopcommerce.com/en/boards/topic/94314/docker-upgrade-installation-page#296108) by **giovannidebona**.

Fix container path for app data

---

src/Libraries/Nop.Services/Catalog/IProductService.cs
src/Libraries/Nop.Services/Catalog/ProductService.cs
src/Presentation/Nop.Web/Areas/Admin/Factories/OrderModelFactory.cs

Refactoring in connection with this issue #6348

Refactor GetWareHouseByIdAsync method

---

src/Libraries/Nop.Core/Infrastructure/NopEngine.cs

This would make it possible to reuse the NopEngine in case it needs to be replaced with a custom/extended one.

NopEngine methods are marked as virtual.

---

Dockerfile

After the last alpine Linux packages build (build date 16.12.2022), Dockerfile got an error in my ci/cd pipeline. The reason for this error, the tiff package is no longer in the "testing" repository. I added the required Package (tiff) from the "main" Repository. After that, my ci/cd pipeline worked.
**Error Details**
Step 69/76 : RUN apk add libgdiplus --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
---> Running in d5c40e0b4b5c
fetch http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
so:libtiff.so.6 (no such package):
required by: …

Edited Dockerfile 

---

src/Build/src/ClearPluginAssemblies/Program.cs

Windows \Plugins\ is hardcoded in the initial dll scans.
When calling ClearPluginAssemblies from linux Plugins folder is not ignored.
Fixing this by replacing \ with Path.DirectorySeparatorChar

Build - ignore Plugins folder for linux

---

src/Libraries/Nop.Core/Http/Extensions/SessionExtensions.cs
src/Libraries/Nop.Services/Authentication/External/ExternalAuthenticationService.cs
src/Libraries/Nop.Services/Payments/IPaymentService.cs
src/Libraries/Nop.Services/Payments/PaymentService.cs
src/Plugins/Nop.Plugin.MultiFactorAuth.GoogleAuthenticator/Controllers/AuthenticationController.cs
src/Plugins/Nop.Plugin.Payments.CyberSource/CyberSourcePaymentMethod.cs
src/Plugins/Nop.Plugin.Payments.CyberSource/Services/EventConsumer.cs
src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Components/PaymentInfoViewComponent.cs
src/Plugins/Nop.Plugin.Payments.PayPalCommerce/PayPalCommercePaymentMethod.cs
src/Plugins/Nop.Plugin.Widgets.FacebookPixel/Services/FacebookPixelService.cs
src/Presentation/Nop.Web/Controllers/CheckoutController.cs
src/Presentation/Nop.Web/Controllers/CustomerController.cs
src/Presentation/Nop.Web/Factories/ShoppingCartModelFactory.cs
src/Presentation/Nop.Web/Views/Customer/_ExternalAuthentication.Errors.cshtml

This change removes a blocking call to the session cache in facebook pixel plugin.
When calling `HttpContext.Session.Get` you have to perform the load beforehand explicitly using `LoadAsync()`, otherwise the call to the session cache will be synchronous, if you're using a distributed cache (for example Redis) this can create big bottlenecks and performance issues.
As described in this article: [Session and state management in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-7.0).
Blocking this call will cause thread starvation. This is what happened to our customers website if Redis response times temporarily increased.
Thread Count:
Page responsetime:
There are some more places where the session cache is called synchronously (Checkout, …

remove-blocking-call-to-session-cache-from-facebookpixel-plugin

---

src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ApplicationBuilderExtensions.cs
src/Presentation/Nop.Web/Program.cs

Since C# 7.1, main can be declared async (see [this article](https://learn.microsoft.com/en-us/archive/blogs/mazhou/c-7-series-part-2-async-main#the-async-main-method)). By using this, we can remove some Task.Wait calls and simplify startup.
Best regards,
Majako
[https://www.majako.se/](https://www.majako.se/) and [https://www.majako.net/](https://www.majako.net/)

Use async main

---

src/Libraries/Nop.Services/Catalog/Caching/ProductCategoryCacheEventConsumer.cs
src/Libraries/Nop.Services/Catalog/CategoryService.cs
src/Libraries/Nop.Services/Catalog/NopCatalogDefaults.cs
src/Libraries/Nop.Services/Extensions.cs
src/Libraries/Nop.Services/Localization/Caching/LocalizedPropertyCacheEventConsumer.cs
src/Libraries/Nop.Services/Localization/LocalizedEntityService.cs
src/Libraries/Nop.Services/Localization/NopLocalizationDefaults.cs
src/Libraries/Nop.Services/Seo/Caching/UrlRecordCacheEventConsumer.cs
src/Libraries/Nop.Services/Seo/NopSeoDefaults.cs
src/Libraries/Nop.Services/Seo/UrlRecordService.cs

Cache categories, localized entities and URL records as lookups for faster retrieval.
Currently, CategoryService, LocalizedEntityService and UrlRecordService cache their respective entities as one big list, and every new lookup is performed by querying this list. Every such operation has a time complexity in $O(n)$, where $n$ is the total number of entities. Since the number of entities in these services can easily number in the thousands, in some cases hundreds of thousands, this quickly becomes a problem.
To address this issue, we instead cache these entities as lookups (specifically, lookup-like dictionaries, since actual lookups cannot be JSON-serialised), reducing retrieval complexity to $O(1)$ (subsequent filtering and sorting of the retrieved lists is negligible, as they are …

Cache lookups instead of lists

---

src/Libraries/Nop.Core/Caching/CacheKeyManager.cs
src/Libraries/Nop.Core/Caching/CachingExtensions.cs
src/Libraries/Nop.Core/Caching/DistributedCacheLocker.cs
src/Libraries/Nop.Core/Caching/DistributedCacheManager.cs
src/Libraries/Nop.Core/Caching/ILocker.cs
src/Libraries/Nop.Core/Caching/IStaticCacheManager.cs
src/Libraries/Nop.Core/Caching/MemoryCacheLocker.cs
src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs
src/Libraries/Nop.Core/Configuration/DistributedCacheConfig.cs
src/Libraries/Nop.Core/Configuration/DistributedCacheType.cs
src/Libraries/Nop.Core/Infrastructure/ConcurrentTrie.cs
src/Libraries/Nop.Services/Caching/MemoryDistributedCacheManager.cs
src/Libraries/Nop.Services/Caching/MsSqlServerCacheManager.cs
src/Libraries/Nop.Services/Caching/RedisCacheManager.cs
src/Libraries/Nop.Services/Caching/RedisConnectionWrapper.cs
src/Libraries/Nop.Services/Caching/RedisSynchronizedMemoryCache.cs
src/Libraries/Nop.Services/Configuration/SettingService.cs
src/Libraries/Nop.Services/Localization/LocalizationService.cs
src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs
src/Presentation/Nop.Web.Framework/Infrastructure/NopStartup.cs
src/Presentation/Nop.Web.Framework/Migrations/UpgradeTo440/LocalizationMigration.cs
src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml
src/Presentation/Nop.Web/Areas/Admin/Models/Settings/DistributedCacheConfigModel.cs
src/Presentation/Nop.Web/Areas/Admin/Views/Setting/_AppSettings.DistributedCache.cshtml
src/Tests/Nop.Tests/BaseNopTest.cs
src/Tests/Nop.Tests/Nop.Core.Tests/Caching/DistributedCacheManagerTests.cs
src/Tests/Nop.Tests/Nop.Core.Tests/Caching/LockerTests.cs
src/Tests/Nop.Tests/Nop.Core.Tests/Caching/MemoryCacheManagerTests.cs
src/Tests/Nop.Tests/Nop.Core.Tests/Infrastructure/ConcurrentTrieTests.cs
src/Tests/Nop.Tests/Nop.Data.Tests/EntityRepositoryTests.cs

This pull request addresses a few performance issues with the current caching infrastructure:
- value factories are wrapped in Lazy instances to avoid spawning multiple acquisition threads performing the same work
- keys are stored in a trie (prefix tree) to optimise removing by prefix, bringing the time complexity of finding keys by prefix down from $O(n|k|)$ to $O(|k|)$, where $n$ is the number of keys and $|k|$ is the length of the prefix
The existing implementations of the distributed cache also suffers from a bug where prefixes are not case-sensitive while the actual cache keys are. This has been fixed so both are case-sensitive.
Furthermore, a more performant implementation of a Redis-based cache is added to make distributed and scalable hosting feasible. This new …

Caching improvements

---

src/Presentation/Nop.Web/wwwroot/css/admin/styles.css

This resolves issue #6549 . 
Previously, when clicking a child-level item in the Admin menu, the caret would move down and to the right: 
Now it stays put: 
**Changes:** 
Line 1354 -- Removed the **min-width** styling. This was being used to move child-items' carets left/inward, and was the cause of this issue. Removing this necessitates lines 1356-1358.
Line 1352 -- Narrowed the scope of the **padding-top** styling, which is needed for the 'circle' icon (this styling pushes it down toward the vertical center-line), but not the 'caret' icon (the styling pushes it down/away from the vertical center-line).
Lines 1356-1358 -- override AdminLTE.io styling to move child-level caret icons left/inward.

change caret icon styling to prevent movement when clicked

---

src/Libraries/Nop.Core/Caching/DistributedCacheManager.cs
src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs

A bug seems to have been introduced regarding handling of null values in the cache, so we have made the following fixes:
- don't cache nulls in DistributedCacheManager
- the `Lazy<Task<T>>` instance from `_memoryCache.GetOrCreate` in MemoryCacheManager cannot be null, but the resulting `T` value might be - since we won't know until the task is awaited, we have to remove the key if the result is null
- as a result of the above, thread interleaving could cause a key to return a null result before it has been removed, so we need to deal with that possibility in the default value overload of `GetAsync`
I believe it would be much better if we did allow for the possibility of null caching and instead dealt with it outside the cache manager, though. Thoughts?
Best regards, …

Undo null caching

---

src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs

I made a mistake with my previous pull request #6618 - because certain methods, such as [UrlRecordService.GetBySlugAsync](https://github.com/nopSolutions/nopCommerce/blob/2c130c60018be960808382496e1aeeeb0a9acc6e/src/Libraries/Nop.Services/Seo/UrlRecordService.cs#L1175) do in some cases try to cache null, instantly removing it again will cause many meaningless events to be posted on the Redis pub/sub channel when using the synchronised cache. See issue #6622.
LocalizationService.GetAllResourceValuesAsync [previously](https://github.com/nopSolutions/nopCommerce/blob/a930e574d545d8aa651ac0119907ae8751283089/src/Libraries/Nop.Services/Localization/LocalizationService.cs#L321) did something similar, and this method in particular caused huge trouble when we incorporated the latest cache changes …

Remove null handling from memory cache

---

src/Libraries/Nop.Core/Configuration/DistributedCacheConfig.cs
src/Libraries/Nop.Services/Caching/RedisSynchronizedMemoryCache.cs
src/Presentation/Nop.Web/App_Data/Localization/defaultResources.nopres.xml
src/Presentation/Nop.Web/Areas/Admin/Models/Settings/DistributedCacheConfigModel.cs
src/Presentation/Nop.Web/Areas/Admin/Views/Setting/_AppSettings.DistributedCache.cshtml

We discovered a potential performance bottleneck in the Redis-synced cache where the instances could be flooded with key events (each of which spawns a new thread on the receiving side) when a lot of keys were deleted at once. To address this, we added message buffering to send updates in batch once per a set interval (default 500 ms). Setting the interval to 0 restores the original behaviour, but since instantaneous propagation cannot be guaranteed (or even achieved) in the first place, this should never be desirable.
Best regards,
Majako [majako.net](https://www.majako.net)

Buffer redis messages

---

src/Libraries/Nop.Core/Caching/DistributedCacheManager.cs
src/Libraries/Nop.Core/Caching/IStaticCacheManager.cs
src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs
src/Tests/Nop.Tests/Nop.Core.Tests/Caching/DistributedCacheManagerTests.cs
src/Tests/Nop.Tests/Nop.Core.Tests/Caching/MemoryCacheManagerTests.cs

In previous versions, one could access a cached value without knowing the type beforehand by doing `await _staticCacheManager.GetAsync<object>(key, () => null)`, but this is no longer possible with the memory-cache manager. Although not used anywhere in the core codebase, it is possible some plugins are making use of this. In order to keep this functionality, we added a non-generic overload of IStaticCacheManager.GetAsync that returns an object instance instead of a typed value.

Add non-generic IStaticCacheManager.GetAsync

---

src/Libraries/Nop.Core/Infrastructure/ConcurrentTrie.cs

@skoshelev since I used a bit mask to index the locks array, we can't just allow any number of locks - only powers of 2 will work for that. It probably doesn't matter here since processor cores always (I think) come in powers of 2 and we have hardcoded the multiple to 8, but it's still wrong. If you insist on allowing arbitrary values of nLocks, we should remove _mask and replace `& _mask` with `% _locks.Length`, as I have done here. Modulus is a slightly slower operation than masking, and since we use powers of 2 anyway I thought we might as well make use of it, but to be fair the time saved is minimal (on the order of a ms or so per million operations) and is overshadowed by basically everything else we do.

Fix array indexing in StripedReaderWriterLock

---

src/Libraries/Nop.Services/Catalog/Caching/ManufacturerCacheEventConsumer.cs
src/Libraries/Nop.Services/Catalog/NopCatalogDefaults.cs

When a manufacturer is edited or deleted, the ProductManufacturersByProductCacheKey is not deleted from the cache. This fixes this error.

Fix product manufacturers cache

---

src/Libraries/Nop.Services/Caching/RedisConnectionWrapper.cs

We are running NopCommerce with a Redis Sentinel cluster.
We have been getting the following exception:
```
StackExchange.Redis.RedisCommandException: Command cannot be issued to a replica: FLUSHDB
```
The problem was that RedisConnectionWrapper.FlushDatabaseAsync was calling FlushDatabaseAsync on the replicas as well. 
I believe that the attached fix fixes the issue.

RedisConnectionWrapper.FlushDatabaseAsync: do not execute "FLUSHDB" on replicas

---

src/Libraries/Nop.Services/Common/Pdf/InvoiceDocument.cs

This fixes #6885 
Prevents a line item from being broken up when line overflows and falls on a page break.

Prevent Page break on line item overflow #6885

---

src/Libraries/Nop.Services/Customers/CustomerService.cs
src/Libraries/Nop.Services/Customers/ICustomerService.cs
src/Libraries/Nop.Services/Customers/NopCustomerServiceDefaults.cs

Recently, we had been experiencing thread-pool starvation on the (MS)SQL server during periods of unusually high traffic, resulting in extremely long response times and even timeouts. These incidents were found to have had a strong correlation with spikes in CustomerRole select queries. As you can see below, during the month leading up to the deployment of this fix, this query was the most time-consuming database operation, being responsible for nearly a third of all query time; it has since been eliminated completely from the list.
Since all customer roles are already cached and no customer is likely to ever have more than a few roles, we could completely forego the expensive table join and limit ourselves to a single select query on CustomerRole on startup.
There is also no compelling …

Use cached customer roles to avoid SQL joins

---

src/Libraries/Nop.Core/Infrastructure/ConcurrentTrie.cs
src/Tests/Nop.Tests/Nop.Core.Tests/Infrastructure/ConcurrentTrieTests.cs

`ConcurrentTrie.Search` previously required the argument key to exactly match an existing key in the tree. This didn't affect any code in the core codebase, but it was unintuitive behaviour. This fix changes the behaviour to conform with the `Prune` method, so that it returns all key-value pairs starting with the supplied prefix; see changes to `ConcurrentTrieTests.CanSearch`.
Best regards,
Majako [https://majako.net/](majako.net) / [https://majako.se/](majako.se)

Make ConcurrentTrie.Search not require exact hit

---

src/Libraries/Nop.Services/Localization/LocalizedEntityService.cs
src/Libraries/Nop.Services/Seo/UrlRecordService.cs

By precomputing only the values we are interested in and removing unnecessary nested cache calls, we can avoid double-caching localised entities and URL records without sacrificing speed. Since there may be a lot of both localised entities and URL records, even the cache keys themselves take unnecessary space in memory and extra time on eviction.
Best regards,
Majako [https://majako.net/](https://github.com/nopSolutions/nopCommerce/pull/majako.net) / [https://majako.se/](https://github.com/nopSolutions/nopCommerce/pull/majako.se)

Improve upon LocalizedEntity and UrlRecord caching

---

src/Libraries/Nop.Services/Catalog/CategoryService.cs

The time complexity of CategoryService.SortCategoriesForTreeAsync is currently $O(n^2)$ for $n$ categories. This is unnecessary, since we can use a lookup with $O(1)$ access instead of filtering a list in $O(n)$ on each recursion.
Although we can no longer sort entries all at once in SQL (potentially shifting execution time to the app server, if the database is hosted separately), it is much cheaper to sort many small lists instead of a single large one (unless the category tree is completely flat, in which case it's the same).
Best regards,
Majako [https://majako.net/](https://github.com/nopSolutions/nopCommerce/pull/majako.net) / [https://majako.se/](https://github.com/nopSolutions/nopCommerce/pull/majako.se)

Optimize SortCategoriesForTreeAsync

---

src/Tests/Nop.Tests/BaseNopTest.cs
src/Tests/Nop.Tests/Nop.Services.Tests/Catalog/PriceFormatterTests.cs
src/Tests/Nop.Tests/Nop.Services.Tests/Customers/CustomerServiceTests.cs
src/Tests/Nop.Tests/Nop.Services.Tests/ExportImport/ExportManagerTests.cs
src/Tests/Nop.Tests/Nop.Services.Tests/Orders/OrderProcessingServiceTests.cs
src/Tests/Nop.Tests/Nop.Services.Tests/Orders/OrderTotalCalculationServiceTests.cs
src/Tests/Nop.Tests/Nop.Tests.csproj
src/Tests/Nop.Tests/Nop.Web.Tests/Admin/Validators/Catalog/CategoryValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Admin/Validators/Catalog/ManufacturerValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Admin/Validators/Vendors/VendorValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Blogs/BlogPostValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Boards/EditForumPostValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Boards/EditForumTopicValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Catalog/ProductEmailAFriendValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Catalog/ProductReviewsValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Common/ContactUsValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Common/ContactVendorValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Customer/ChangePasswordValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Customer/CustomerInfoValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Customer/LoginValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Customer/PasswordRecoveryConfirmValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Customer/PasswordRecoveryValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Customer/RegisterValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/Install/InstallValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/PrivateMessages/SendPrivateMessageValidatorTests.cs
src/Tests/Nop.Tests/Nop.Web.Tests/Public/Validators/ShoppingCart/WishlistEmailAFriendValidatorTests.cs

fix (Tests): Fix Stackoverflow in tests and other issues.
- Update to NUnit 4
- Register missing services
- Change scope of IDataProviderManager (causing a stackoverflow in net8)
- Reduce state over tests by changing OneTimeSetup/Teardown to Setup/Teardown. TearDown
- Reduce coupling to DI for resolving Validators, Construct in test with dependencies (still via DI for now)
- Reduce the GetService Magic where it will construct a dependency even when it can't resolve it.  Either be explicit or register it.
- Some tests were using the implmenetation class not the interface so DI was not working (but the GetService magic filled the gap when the DI could not resolve from container.)
Resolves #6948

fix (unittests) #6948 Resolve issues with tests creating a stack overflow. Upgrade to NUnit4

---

src/Libraries/Nop.Services/Caching/RedisSynchronizedMemoryCache.cs

- Use Patternmode for redis.
Part Resolves #7034 
(As described below, Service is codegen'ed so not useful to fix manually)

fix(BuildWarnings): Fix build warnings for redis CS0618 #7034

---

src/Libraries/Nop.Services/Html/HtmlFormatter.cs

In `Nop.Services.HtmlFormatter`, the documentation comment for the utility method `EnsureOnlyAllowedHtml` includes an incorrect description for the return value.
The method signature is `protected static string EnsureOnlyAllowedHtml(string text)`, and the method implementation returns the validated text with all invalid tags removed. However, the documentation indicates that the method returns a `bool` value to indicate the validity of the original text.
Actual documentation: `<returns>True - if the text contains only valid tags, false otherwise</returns>`.
Expected documentation: `<returns>Validated text with all invalid tags removed</returns>`.
- Modify `EnsureOnlyAllowedHtml` `text` parameter description for consistency with same parameter in other methods.
- Modify …

#7048 Fix incorrect documentation in HtmlFormatter

---

src/Libraries/Nop.Core/Nop.Core.csproj
src/Plugins/Nop.Plugin.ExternalAuth.Facebook/Nop.Plugin.ExternalAuth.Facebook.csproj
src/Presentation/Nop.Web.Framework/Nop.Web.Framework.csproj

Bump Microsoft.AspNetCore and Microsoft.Extensions.Caching to 8.0.1
- Release notes: https://devblogs.microsoft.com/dotnet/january-2024-updates/
Bump LigerShark.WebOptimizer.Core to 3.0.396 and WebMarkupMin to 2.15.3
- https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.15.3
- https://github.com/ligershark/WebOptimizer/commits/master/
Bump Autofac.Extensions.DependencyInjection to 9
- Release notes: https://github.com/autofac/Autofac.Extensions.DependencyInjection/releases/tag/v9.0.0
Relates to #196

task(Deps): Update Microsoft.Aspnet, LigerShark, Autofac.Extensions 

---

src/Libraries/Nop.Data/Nop.Data.csproj

Upgrade SqlClient to 5.1.4 to mitigate CVE
[CVE-2024-0056](https://techcommunity.microsoft.com/t5/sql-server-blog/released-security-updates-for-microsoft-data-sqlclient-and/ba-p/4024264)
As it is a minor point release, there should be no compatability issues.
Resolves #7024

fix(Security): Upgrade SqlClient to 5.1.4 to mitigate CVE-2024-0056

---

src/Presentation/Nop.Web/package-lock.json
src/Presentation/Nop.Web/package.json

Upgrade tinymce lib to 5.10.9 to mitigate the vulnerability [CVE-2023-48219](https://www.cve.org/CVERecord?id=CVE-2023-48219)
Resolves #7017

fix (TinyMCE): Update tinymce to 5.10.9 to fix CVE-2023-48219 

---

src/Plugins/Nop.Plugin.Pickup.PickupInStore/Validators/StorePickupPointValidator.cs

Change to non-deprecated `PrecisionScale` method in `FluentValidation`.
See https://github.com/FluentValidation/FluentValidation/issues/2030 for reason.

fix (StorePickup/Validation): Change to non-deprecated method in FluentValidation.

---

src/Libraries/Nop.Core/Domain/Shipping/ShipmentTrackingNumberSetEvent.cs
src/Presentation/Nop.Web/Areas/Admin/Controllers/OrderController.cs

Many times, we need to know that any tracking number has been set for a shipment; For example notify customer about that or give him/her this tracking number.
So I have added this event ad called it when creating new shipment (if has any) or when set tracking number (if new one added).
Many number of my customers need it and I decided to add it to the nopCommerce source code except in my custom projects.

Add new event of 'ShipmentTrackingNumberSetEvent'

---

src/Libraries/Nop.Services/Seo/UrlRecordService.cs

I cleaned up UrlRecordService by getting rid of unicode string parsing and locks, and simplified name formatting by replacing while/replace with regex.
However, I must ask what the rationale behind initialising `_seoCharacterTable` like that is, instead of just directly assigning it as readonly? I assume it is for the init method to be possibly overridden in a subclass, but if that is really necessary, wouldn't it be better to break it out into its own singleton class? That could then be modified and replaced in the DI container if necessary, without a subclass changing the behaviour of its superclass by changing a static member. My IDE is complaining that "Non-constant fields should not be visible", and I am inclined to agree.
Best regards,
Rickard von Haugwitz,
Majako …

Refactor and clean up UrlRecordService

---

src/Libraries/Nop.Core/ComponentModel/GenericListTypeConverter.cs
src/Tests/Nop.Tests/Nop.Core.Tests/ComponentModel/GenericListTypeConverterTests.cs

This pull request introduces a refactoring to the GenericListTypeConverter.ConvertTo method (#7198). The primary changes involve:
Replacing the manual loop with a more concise approach using Select and string.Join. This optimizes performance and reduces the risk of errors related to manual concatenation.
Utilizing CultureInfo.InvariantCulture consistently to ensure culture-independent string conversion.
Implementing a unit test (CanConvertNullToString) to verify the converter's behavior when handling null input.
These improvements enhance the overall maintainability and readability of the code while ensuring expected behavior.

Refactor ConvertTo method in GenericListTypeConverter

---

src/Tests/Nop.Tests/AssemblyInfo.cs

When running tests within a GitHub Action runner, tests intermittently fail with `ObjectDisposedException` within the database provider.  This appears to be a concurrency-related problem.  Configuring NUnit to only run a single test at a time fixes the problem.

Fix CI tests due to concurrency problems

---

src/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Controllers/FixedByWeightByTotalController.cs
src/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Services/ShippingByWeightByTotalService.cs

Some times, it's need to filter shipping rates with all shipping methods, not only one.

Possibility to do not select 'ShippingMethod' to filter in 'ShippingByWeightByTotal' plugin

---

src/Libraries/Nop.Data/Extensions/AsyncIQueryableExtensions.cs
src/Libraries/Nop.Services/Authentication/External/ExternalAuthenticationService.cs
src/Libraries/Nop.Services/Catalog/CategoryService.cs
src/Libraries/Nop.Services/Catalog/ManufacturerService.cs
src/Libraries/Nop.Services/Catalog/ProductService.cs
src/Libraries/Nop.Services/Catalog/ProductTagService.cs
src/Libraries/Nop.Services/Discounts/DiscountService.cs
src/Libraries/Nop.Services/Forums/ForumService.cs
src/Libraries/Nop.Services/Installation/InstallationService.cs
src/Libraries/Nop.Services/Localization/LocalizationService.cs
src/Libraries/Nop.Services/Messages/QueuedEmailService.cs
src/Libraries/Nop.Services/Orders/RewardPointService.cs
src/Libraries/Nop.Services/Security/AclService.cs
src/Libraries/Nop.Services/Stores/StoreMappingService.cs
src/Libraries/Nop.Services/Topics/TopicService.cs
src/Plugins/Nop.Plugin.Misc.Zettle/Services/ZettleRecordService.cs
src/Plugins/Nop.Plugin.Tax.Avalara/Services/ItemClassificationService.cs

Using the [Shane32.Analyzers NuGet package](https://www.nuget.org/packages/Shane32.Analyzers), all implicit casts of `IQuerable` to `IEnumerable` can be detected and fixed.  This PR does not add the NuGet package, but fixes many of the detected errors.
I did not attempt to fix errors within synchronous methods, such as within data migration classes.

Convert various sync calls to async

---

src/Libraries/Nop.Services/Orders/OrderProcessingService.cs

this is the fix for #5826 
Steps to reproduce the problem:
I have a problem with my shopping cart total decreasing every time I reorder an order including products with CustomEredenteredPrice options enabled. It only happens when PricesIncludeTax is enabled in taxsettings.
Found out that the ReOrderAsync function in the OrderProcessingService is always using
orderItem.UnitPriceExclTax regardless of taxsettings.
source : : https://www.nopcommerce.com/en/boards/topic/91910/reorder-uses-prices-exluding-tax-for-customer-entered-prices-regardless-of-taxsettings

Updated the ReOrderAsync method to handle price include tax

---

src/Libraries/Nop.Services/Caching/RedisCacheManager.cs

Refactored the `RemoveByPrefixAsync` method in `RedisCacheManager` to use `await db.KeyDeleteAsync(keys.ToArray());`, leveraging _StackExchange.Redis_'s async API for non-blocking execution.

Use async KeyDeleteAsync in RedisCacheManager.RemoveByPrefixAsync

---

src/Libraries/Nop.Services/Catalog/ManufacturerService.cs

Replaced the synchronous `ToList()` method with `ToListAsync()` in the GetProductManufacturersByProductIdAsync method within ManufacturerService

Use ToListAsync for async query execution

---

src/Libraries/Nop.Services/Stores/StoreMappingService.cs

Refactored the `IsEntityMappingExistsAsync `method to use `query.AnyAsync` for asynchronous query execution, ensuring alignment with best practices for efficient async operations.

Optimize Async Query Handling in IsEntityMappingExistsAsync

---

src/Libraries/Nop.Services/Localization/LocalizationService.cs

Refactored the `ImportResourcesFromXmlAsync` method in `LocalizationService` to use `ToDictionaryAsync` for efficient async query execution and dictionary creation. Removed unnecessary sorting

Refactor to use ToDictionaryAsync for async execution

---

src/Libraries/Nop.Services/Messages/MessageTemplateService.cs

Moved store mapping filtering to the query level to improve performance and reduce in-memory filtering when retrieving message templates

Optimize Message Template Query by Applying Store Mapping at Database Level

---

src/Libraries/Nop.Services/Orders/IOrderProcessingService.cs
src/Libraries/Nop.Services/Orders/OrderProcessingService.cs
src/Libraries/Nop.Services/Payments/IPaymentService.cs
src/Libraries/Nop.Services/Payments/PaymentService.cs
src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Services/PayPalCommerceServiceManager.cs
src/Presentation/Nop.Web/Controllers/CheckoutController.cs
src/Tests/Nop.Tests/Nop.Services.Tests/Orders/OrderProcessingServiceTests.cs
src/Tests/Nop.Tests/Nop.Services.Tests/Payments/PaymentServiceTests.cs

Move GenerateOrderGuidAsync to IOrderProcessingService

---

src/Libraries/Nop.Services/Media/PictureService.cs

This is an edge case - my plugin generates invoices in a background task, in which the HttpContext is null, which produces `System.NullReferenceException: Object reference not set to an instance of an object.` 
`HttpContext` should have a null check just like `Request` does and this should not have any negative side effects, since null is just converted to `string.Empty` anyway.

Update PictureService.cs - NullReferenceException remedy

---

src/Libraries/Nop.Services/Catalog/ProductService.cs

This PR removes an unnecessary join in `ClearDiscountProductMappingAsync` and optimizes query execution by using `ToListAsync()`

Refactor ClearDiscountProductMappingAsync to remove unnecessary join and optimize query

---

src/Presentation/Nop.Web/Areas/Admin/Views/Order/_OrderDetails.BillingShipping.cshtml
src/Presentation/Nop.Web/Areas/Admin/Views/_ViewImports.cshtml

The "Shipments" block on the order edit page is hidden when the current user does not have the "View Shipments" permission.

Hide "Shipments" block for users without "View Shipments" permission on the order edit page

---

src/Presentation/Nop.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.cshtml
src/Presentation/Nop.Web/Areas/Admin/Views/_ViewImports.cshtml

Checking StandardPermission.Orders.GIFT_CARDS_CREATE_EDIT_DELETE before rendering the usage history block

Render usage history on the gift card edit page based on the associated permission

---

src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.cshtml
src/Presentation/Nop.Web/Areas/Admin/Views/_ViewImports.cshtml

The "Purchased with orders" block on the product edit page is hidden when the current user does not have the "View orders" permission.

Hide "Purchased with orders" block for users without "View orders" permission

---

src/Libraries/Nop.Data/Migrations/UpgradeTo490/AddIndexesMigration.cs

This bug caused a database exception because the code attempted to create an index that already existed.

Fix: correct index existence check for database migration in v4.9.0

---

src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ApplicationBuilderExtensions.cs

It was inspired by UseStatusCodePagesWithReExecute method from Microsoft.AspNetCore.Builder.StatusCodePagesExtensions class.
Now, the non-existing URL does not redirect with a 302 but directly returns staus 404.
This resolves #6966

Do not redirect to 404 with 302

---

src/Libraries/Nop.Core/Caching/IShortTermCacheManager.cs
src/Libraries/Nop.Core/ComponentModel/ReaderWriteLockDisposable.cs
src/Libraries/Nop.Core/Configuration/AzureBlobConfig.cs
src/Libraries/Nop.Data/DataProviders/MsSqlDataProvider.cs

This pull request addresses several minor typos identified in the project documentation.

Fix Typos in Documentation

---

src/Libraries/Nop.Services/Localization/LocalizationService.cs

This PR contains the following points
- Removed the `unused` language parameter from `LoadLocaleResourcesFromStream` method in `LocalizationService` class
Issue link: https://github.com/nopSolutions/nopCommerce/issues/7653

refactor: removed the unused language parameter #7653

---

src/Libraries/Nop.Services/Media/RoxyFileman/RoxyFilemanFileProvider.cs

Replaced the deprecated SKBitmap.ScalePixels method that used SKFilterQuality.None with the recommended SKSamplingOptions (SKFilterMode.Nearest, SKMipmapMode.None), which preserves the same ScalePixels behavior.
In SKPaint.cs, SKFilterQuality.None maps to new SKSamplingOptions(SKFilterMode.Linear, SKMipmapMode.Linear) (see attached screenshot)

Replace obsolete SKBitmap.ScalePixels with recommended SKSamplingOptions in RoxyFilemanFileProvider

---

src/Libraries/Nop.Services/Media/PictureService.cs

Replaced the deprecated SKBitmap.Resize method that used SKFilterQuality.Medium with the recommended SKSamplingOptions(SKFilterMode.Linear, SKMipmapMode.Linear), which preserves the same image resize behavior.
In SKPaint.cs, SKFilterQuality.Medium maps to new SKSamplingOptions(SKFilterMode.Linear, SKMipmapMode.Linear) (see attached screenshot)

Replace obsolete SKBitmap.Resize method in PictureService

---

src/Libraries/Nop.Services/Catalog/CategoryService.cs
src/Libraries/Nop.Services/Catalog/ICategoryService.cs
src/Libraries/Nop.Services/Catalog/IManufacturerService.cs
src/Libraries/Nop.Services/Catalog/IProductAttributeService.cs
src/Libraries/Nop.Services/Catalog/ManufacturerService.cs
src/Libraries/Nop.Services/Catalog/ProductAttributeService.cs
src/Libraries/Nop.Services/ExportImport/ImportManager.cs
src/Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs

Previously, entity deletions were executed one by one using individual async calls, which introduced unnecessary database round-trips. This PR optimizes the following methods to delete lists of entities in bulk within a single transaction:
`DeleteProductAttributeValuePicturesAsync`
`DeleteProductCategoriesAsync`
`DeleteProductManufacturersAsync`
This improves performance.

Optimize entity deletions in multiple methods by batching operations into single transactions

---

src/Presentation/Nop.Web/Areas/Admin/Controllers/PluginController.cs

🛠️ What did we do to fix it?
We moved the PluginUpdatedEvent trigger to the very end of the POST method — after:
The plugin's enabled/disabled logic runs,
All related settings are saved,
Activity log is recorded.
This ensures that the plugin is in its final and consistent state when the event is published, and all event subscribers get accurate information.
- await _eventPublisher.PublishAsync(new PluginUpdatedEvent(pluginDescriptor));
// (Previously triggered too early)
...
+ await _customerActivityService.InsertActivityAsync(...);
+ await _eventPublisher.PublishAsync(new PluginUpdatedEvent(pluginDescriptor));
// (Now triggered at the correct place, after all updates)

We moved the PluginUpdatedEvent trigger to the very end of the POST;
